### ISSUE TITLE
Morphemes glossed with numbers should be grammatical, not lexical morphemes

### ISSUE THREAD

**Issue by fmatter** [cldf/pyigt#10]
Since the distinction is made between grammatical and lexical morphemes, a gloss like `1` or `1SG` (not tested) or `1>3` should be categorized as grammatical, just like `ERG`. I noticed it in the results of `corpus.get_wordlist()`; I am not sure if this categorization happens elsewhere.

**Comment by LinguList** [comment]
Depends on your perspective. For me, as one who wants to pull out a Swadesh list of the Qiang data, I count them as non-grammatical.

**Comment by LinguList** [comment]
What counts as grammatical and was not depends on a regex, which can be configured:

https://github.com/cldf/pyigt/blob/ed75e26099dc940ee3cea3ffbc39be7394626fc4/src/pyigt/igt.py#L43-L44

As you can do by triggering the label_pattern:

https://github.com/cldf/pyigt/blob/ed75e26099dc940ee3cea3ffbc39be7394626fc4/src/pyigt/igt.py#L36

If 1SG is matched, but 1sg would not be matched, 1 would not be matched (for good reasons, as it can even be a number).

**Comment by fmatter** [comment]
> Depends on your perspective. For me, as one who wants to pull out a Swadesh list of the Qiang data, I count them as non-grammatical.

…right, I hadn't considered that perspective :)

> What counts as grammatical and was not depends on a regex, which can be configured

So do we modify `label_pattern` in the `igt.py` file? Or where in the workflow would that happen?

**Comment by LinguList** [comment]
It depends on your application. If you want to follow the cldf-schema,
with the commands interface (which is quite comfortable, but of course
tedious, if you do it for 50 datasets), you would modify your params
there. So you could specify in this line of the cldf-example-repo for
lapollaqiang:

https://github.com/cldf-datasets/lapollaqiang/blob/40bcba31a65b675a15d2dcac5fae7901619162fc/commands/workflow.py#L13-18

Inside Python scripts you can of course also use it more freely.

**Comment by fmatter** [comment]
Aaah, so I would pass a custom `CorpusSpec` instance like so?

```
class MyCorpusSpec(object):
    …
    label_pattern = attr.ib(default=re.compile('^([A-Z]+|([1-3](DL|PL|SG)))$'))
    …

text = Corpus.from_cldf(ds.cldf_reader(), spec=MyCorpusSpec)
```

?
