### ISSUE TITLE
Single IGTs do not contain the translation

### ISSUE THREAD

**Issue by fmatter** [cldf/pyigt#11]
Operations like 

```
ds = Dataset()
texts = Corpus.from_cldf(ds.cldf_reader())
for igt in texts:
    print(igt)
```

or, on the command line

```
igt ls cldf/cldf-metadata.json Text_ID=1
```

only print the object and gloss line. The `Translated_Text` is only contained in`IGT.properties`. Is this intentional?

**Comment by LinguList** [comment]
Yes, in most cases, translations are poorly aligned with any higher level of order, such as the phrase or the sentence. If it can be shown that there is a substantial amount of data where translation texts are thoroughly aligned (but this does not hold for resources like ODIN, where I checked), we may consider adjusting this behavior.
